apiVersion: apps/v1
# api version allows us access to different objects
kind: Deployment
# type of object
metadata:
  name: client-deployment
spec:
  replicas: 1
  # number of instances of objects
  selector:
    matchLabels:
      component: web
      # used to match with template below
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: stephengrider/multi-client
          # image build from docker hub
          ports:
            - containerPort: 9999
